name: Release

on:
    push:
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'

            - name: Install deps
              run: npm ci

            - name: Build
              run: npm run build

            - name: Extract changelog entry
              run: |
                  RAW_VERSION=${GITHUB_REF_NAME#v}

                  # если версия заканчивается на "-test" → обрезаем
                  if [[ "$RAW_VERSION" == *"-test" ]]; then
                    VERSION=${RAW_VERSION%-test}
                  else
                    VERSION=$RAW_VERSION
                  fi

                  echo "Looking for version: $VERSION (from tag $RAW_VERSION)"

                  # Вырезаем блок changelog-а для версии
                  awk "/^## \\[$VERSION\\]/,/^## \\[/" CHANGELOG.md | sed '$d' > RELEASE_NOTES.md || true

                  # Если это последняя версия в changelog
                  if [ ! -s RELEASE_NOTES.md ]; then
                    awk "/^## \\[$VERSION\\]/,0" CHANGELOG.md > RELEASE_NOTES.md || true
                  fi

                  # Fallback
                  if [ ! -s RELEASE_NOTES.md ]; then
                    echo "⚠️ No changelog entry found, using default message"
                    echo "Release $RAW_VERSION" > RELEASE_NOTES.md
                  fi

                  echo "---- RELEASE NOTES ----"
                  cat RELEASE_NOTES.md

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  body_path: RELEASE_NOTES.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to npm
              if: github.event_name != 'workflow_dispatch'
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
