name: Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'

            - name: Install deps
              run: npm ci

            - name: Build
              run: npm run build

            - name: Extract changelog entry
              id: changelog
              run: |
                  VERSION=${GITHUB_REF_NAME#v}
                  echo "Looking for version: $VERSION"
                  awk "/## \\[$VERSION\\]/,/^## \\[/" CHANGELOG.md | sed '$d' > RELEASE_NOTES.md || true
                  if [ ! -s RELEASE_NOTES.md ]; then
                    echo "⚠️ No changelog entry found, using default message"
                    echo "Release $VERSION" > RELEASE_NOTES.md
                  fi
                  echo "notes<<EOF" >> $GITHUB_OUTPUT
                  cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  body: ${{ steps.changelog.outputs.notes }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
