name: Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - run: npm ci
            - run: npm run test:unit

    e2e-tests:
        runs-on: ubuntu-latest
        needs: unit-tests
        if: github.event_name == 'pull_request' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        strategy:
            matrix:
                node: [20, 22]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm
            - run: npm ci
            - run: npm run build
            - run: npm run test:e2e
